package confgen

import (
	"fmt"
	"strings"

	"github.com/splunk-capacity-planning/scpcalc/internal/model"
)

// Render builds a draft indexes.conf from a legacy single-index result.
func Render(in model.Input, res model.Result) string {
	plan := in.ToPlan()
	pr := model.PlanResult{
		CompressionFactor: res.CompressionFactor,
		Indexes: []model.IndexResult{{
			IndexName:              in.IndexName,
			MaxTotalDataSizeMB:     res.MaxTotalDataSizeMB,
			HomePathMaxDataSizeMB:  res.HomePathMaxDataSizeMB,
			FrozenTimePeriodInSecs: res.FrozenTimePeriodInSecs,
			MaxDataSize:            res.MaxDataSize,
		}},
		HotVolumeMB:       res.HomePathMaxDataSizeMB,
		ColdVolumeMB:      res.MaxTotalDataSizeMB - res.HomePathMaxDataSizeMB,
		SummariesVolumeMB: 0,
	}
	return RenderPlan(plan, pr)
}

// RenderPlan builds volumes + all index / summary stanzas.
func RenderPlan(p model.PlanInput, res model.PlanResult) string {
	var b strings.Builder
	writeHeader(&b, p, res)

	fmt.Fprintf(&b, "[volume:hotwarm]\npath = %s\nmaxVolumeDataSizeMB = %d\n# Hot/warm (+ DMA colocated by default on reference hardware)\n\n", p.HotPath, max64(res.HotVolumeMB, 1))
	fmt.Fprintf(&b, "[volume:cold]\npath = %s\nmaxVolumeDataSizeMB = %d\n# Cold searchable retention\n\n", p.ColdPath, max64(res.ColdVolumeMB, 1))

	sumMB := res.SummariesVolumeMB
	if sumMB <= 0 && (p.WantDMA() || hasSummary(res)) {
		sumMB = 1
	}
	if sumMB > 0 {
		fmt.Fprintf(&b, "[volume:summaries]\npath = %s\nmaxVolumeDataSizeMB = %d\n# Prefer SSD/NVMe; keep separate from cold (DMA/tstats + summary indexes)\n\n", p.SummariesPath, max64(sumMB, 1))
	}

	if p.SmartStore {
		remote := strings.TrimSpace(p.RemotePath)
		if remote == "" {
			remote = "s3://YOUR_BUCKET/splunk"
		}
		fmt.Fprintf(&b, "# --- SmartStore (docs/en/02 §5) ---\n")
		fmt.Fprintf(&b, "# Remote_Store_GB ≈ D × R × Comp (see design.remote_store_gb).\n")
		fmt.Fprintf(&b, "# Each cluster needs a unique remote path. Network target: 10 Gbps/indexer.\n")
		fmt.Fprintf(&b, "[volume:remote]\nstorageType = remote\npath = %s\n# Configure remote.s3.* (or provider) credentials in indexes.conf / server.conf as required\n\n", remote)
	}

	emitTstats := p.WantDMA()
	for _, ix := range res.Indexes {
		writeIndex(&b, p, ix.IndexName, ix.HomePathMaxDataSizeMB, ix.ColdPathMaxDataSizeMB, ix.MaxTotalDataSizeMB, ix.FrozenTimePeriodInSecs, ix.MaxDataSize, "primary", emitTstats)
		if ix.SummaryIndexName != "" && ix.SummaryMaxTotalMB > 0 {
			writeIndex(&b, p, ix.SummaryIndexName, ix.SummaryHomeMaxMB, ix.SummaryColdMaxMB, ix.SummaryMaxTotalMB, ix.SummaryFrozenSecs, "auto", "summary", false)
		}
	}
	return b.String()
}

func writeHeader(b *strings.Builder, p model.PlanInput, res model.PlanResult) {
	b.WriteString("# Generated by SCPcalc — review before production use\n")
	b.WriteString("# Author: Mohammad Mirasadollahi\n")
	b.WriteString("# GitHub: https://github.com/Mohammad-Mirasadollahi/splunk-capacity-planning\n")
	b.WriteString("# Docs:   https://mohammad-mirasadollahi.github.io/splunk-capacity-planning/\n")
	b.WriteString("# Calc:   https://mohammad-mirasadollahi.github.io/splunk-capacity-planning/calc/\n")
	b.WriteString("# Formulas: knowledge pack docs/en/02 + docs/en/05\n")
	b.WriteString("#\n")
	b.WriteString("# --- Plan snapshot (from your wizard settings) ---\n")

	// Topology
	if p.IndexerCluster {
		fmt.Fprintf(b, "# Topology: indexer cluster ON · RF=%d · SF=%d", maxInt(p.RF, 1), maxInt(p.SF, 1))
	} else {
		b.WriteString("# Topology: standalone indexers (no indexer cluster)")
	}
	if p.SearchHeadCluster {
		b.WriteString(" · SHC ON")
	} else {
		b.WriteString(" · SHC OFF")
	}
	b.WriteString("\n")

	peers := res.IndexerPeers
	if peers < 1 && res.Design != nil && res.Design.NIDX > 0 {
		peers = res.Design.NIDX
	}
	if peers < 1 {
		peers = 1
	}
	nSh := 0
	if res.Design != nil {
		nSh = res.Design.NSH
	}
	if nSh <= 0 {
		nSh = p.NSh
	}
	fmt.Fprintf(b, "# Nodes: N_IDX≈%d", peers)
	if nSh > 0 {
		fmt.Fprintf(b, " · N_SH≈%d", nSh)
	}
	apps := make([]string, 0, 4)
	if p.HasES {
		apps = append(apps, "ES")
	}
	if p.HasITSI {
		apps = append(apps, "ITSI")
	}
	if p.WantDMA() {
		apps = append(apps, "DMA")
	}
	if p.SmartStore {
		apps = append(apps, "SmartStore")
	}
	if len(apps) > 0 {
		fmt.Fprintf(b, " · apps: %s", strings.Join(apps, ", "))
	}
	b.WriteString("\n")

	ret := p.RetentionDays
	if ret <= 0 {
		ret = 90
	}
	hw := p.HotWarmDays
	if hw <= 0 {
		hw = 30
	}
	if hw > ret {
		hw = ret
	}
	coldDays := ret - hw
	headroom := p.Headroom
	if headroom <= 0 {
		headroom = 1.2
	}
	fmt.Fprintf(b, "# Retention: searchable %dd · hot/warm %dd · cold %dd (auto) · headroom %.2f\n", ret, hw, coldDays, headroom)

	if p.ArchiveFrozen {
		fp := strings.TrimSpace(p.FrozenPath)
		if fp == "" {
			fp = "/frozen"
		}
		fmt.Fprintf(b, "# Freeze policy: ARCHIVE on freeze → coldToFrozenDir under %s\n", fp)
	} else {
		b.WriteString("# Freeze policy: DELETE on freeze (no coldToFrozenDir — Splunk default)\n")
	}

	comp := res.CompressionFactor
	if comp <= 0 {
		comp = p.Compression
	}
	if comp > 0 {
		fmt.Fprintf(b, "# Compression factor used: %.3f", comp)
		if p.Compression > 0 {
			b.WriteString(" (measured override)")
		} else if p.IndexerCluster {
			b.WriteString(" (from RF/SF model)")
		} else {
			b.WriteString(" (standalone default ~0.5)")
		}
		b.WriteString("\n")
	}

	if res.TotalDailyRawGB > 0 {
		fmt.Fprintf(b, "# Volume: total raw ≈ %.3f GB/day · on-disk ≈ %.3f GB/day · searchable ≈ %.3f TB\n",
			res.TotalDailyRawGB, res.TotalDailyOnDiskGB, res.TotalSearchableTB)
	} else if p.TotalDailyGB > 0 {
		fmt.Fprintf(b, "# Volume input: total_daily_gb=%.3f (sources may scale to this)\n", p.TotalDailyGB)
	}

	nIdx := len(res.Indexes)
	if nIdx > 0 {
		names := make([]string, 0, nIdx)
		for _, ix := range res.Indexes {
			if ix.IndexName != "" {
				names = append(names, ix.IndexName)
			}
		}
		fmt.Fprintf(b, "# Indexes in this conf: %d", nIdx)
		if len(names) > 0 && len(names) <= 12 {
			fmt.Fprintf(b, " (%s)", strings.Join(names, ", "))
		}
		b.WriteString("\n")
	}

	fmt.Fprintf(b, "# Paths: hot=%s · cold=%s · summaries=%s",
		orPath(p.HotPath, "/hot"), orPath(p.ColdPath, "/cold"), orPath(p.SummariesPath, "/summaries"))
	if p.ArchiveFrozen {
		fmt.Fprintf(b, " · frozen=%s", orPath(p.FrozenPath, "/frozen"))
	}
	if p.SmartStore {
		rp := strings.TrimSpace(p.RemotePath)
		if rp == "" {
			rp = "s3://YOUR_BUCKET/splunk"
		}
		fmt.Fprintf(b, " · remote=%s", rp)
	}
	b.WriteString("\n")

	if peers > 1 {
		fmt.Fprintf(b, "# Size fields below are PER PEER (cluster total ÷ N_IDX=%d).\n", peers)
	} else {
		b.WriteString("# Size fields below are for a single indexer (not divided by peer count).\n")
	}
	b.WriteString("# coldPath.maxDataSizeMB is derived automatically: maxTotal − homePath.\n")
	b.WriteString("# Event-size defaults are editable planning estimates — measure yours before production.\n")
	b.WriteString("\n")
}

func orPath(v, fallback string) string {
	v = strings.TrimSpace(v)
	if v == "" {
		return fallback
	}
	return v
}

func maxInt(a, b int) int {
	if a > b {
		return a
	}
	return b
}

func hasSummary(res model.PlanResult) bool {
	for _, ix := range res.Indexes {
		if ix.SummaryIndexName != "" {
			return true
		}
	}
	return false
}

func writeIndex(b *strings.Builder, p model.PlanInput, name string, homeMB, coldMB, totalMB, frozenSecs int64, maxData, kind string, emitTstats bool) {
	idx := SanitizeIndex(name)
	fmt.Fprintf(b, "[%s]\n", idx)
	if kind == "summary" {
		fmt.Fprintf(b, "homePath = volume:summaries/%s/db\n", idx)
		fmt.Fprintf(b, "coldPath = volume:summaries/%s/colddb\n", idx)
		fmt.Fprintf(b, "thawedPath = %s/%s/thaweddb\n", strings.TrimRight(p.SummariesPath, "/"), idx)
	} else if p.SmartStore {
		fmt.Fprintf(b, "homePath = volume:hotwarm/%s/db\n", idx)
		fmt.Fprintf(b, "coldPath = volume:hotwarm/%s/colddb\n", idx) // SmartStore: warm typically local cache path family
		fmt.Fprintf(b, "thawedPath = %s/%s/thaweddb\n", strings.TrimRight(p.ColdPath, "/"), idx)
		fmt.Fprintf(b, "remotePath = volume:remote/%s\n", idx)
	} else {
		fmt.Fprintf(b, "homePath = volume:hotwarm/%s/db\n", idx)
		fmt.Fprintf(b, "coldPath = volume:cold/%s/colddb\n", idx)
		fmt.Fprintf(b, "thawedPath = %s/%s/thaweddb\n", strings.TrimRight(p.ColdPath, "/"), idx)
	}
	if coldMB < 0 {
		coldMB = 0
	}
	if coldMB == 0 && totalMB > homeMB {
		coldMB = totalMB - homeMB
	}
	fmt.Fprintf(b, "homePath.maxDataSizeMB = %d\n", homeMB)
	fmt.Fprintf(b, "coldPath.maxDataSizeMB = %d\n", coldMB)
	fmt.Fprintf(b, "# coldPath.maxDataSizeMB is derived: maxTotalDataSizeMB − homePath.maxDataSizeMB\n")
	fmt.Fprintf(b, "maxTotalDataSizeMB = %d\n", totalMB)
	fmt.Fprintf(b, "frozenTimePeriodInSecs = %d\n", frozenSecs)
	fmt.Fprintf(b, "maxDataSize = %s\n", maxData)
	if p.ArchiveFrozen {
		fmt.Fprintf(b, "coldToFrozenDir = %s/%s/frozendb\n", strings.TrimRight(p.FrozenPath, "/"), idx)
	} else {
		b.WriteString("# coldToFrozenDir omitted — default freeze deletes (set archive_frozen=true to archive)\n")
	}
	if kind == "primary" && emitTstats {
		fmt.Fprintf(b, "tstatsHomePath = volume:summaries/%s/datamodel_summary\n", idx)
	}
	b.WriteString("\n")
}

// SanitizeIndex maps a label to a safe indexes.conf stanza name.
func SanitizeIndex(name string) string {
	name = strings.TrimSpace(name)
	if name == "" {
		return "windows"
	}
	var out strings.Builder
	for _, r := range name {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' || r == '-' {
			out.WriteRune(r)
		} else {
			out.WriteByte('_')
		}
	}
	s := out.String()
	if s == "" {
		return "windows"
	}
	return s
}

func max64(a, b int64) int64 {
	if a > b {
		return a
	}
	return b
}
