package confgen

import (
	"fmt"
	"strings"

	"github.com/splunk-capacity-planning/scpcalc/internal/model"
)

// Render builds a draft indexes.conf from a legacy single-index result.
func Render(in model.Input, res model.Result) string {
	plan := in.ToPlan()
	pr := model.PlanResult{
		CompressionFactor: res.CompressionFactor,
		Indexes: []model.IndexResult{{
			IndexName:              in.IndexName,
			MaxTotalDataSizeMB:     res.MaxTotalDataSizeMB,
			HomePathMaxDataSizeMB:  res.HomePathMaxDataSizeMB,
			FrozenTimePeriodInSecs: res.FrozenTimePeriodInSecs,
			MaxDataSize:            res.MaxDataSize,
		}},
		HotVolumeMB:       res.HomePathMaxDataSizeMB,
		ColdVolumeMB:      res.MaxTotalDataSizeMB - res.HomePathMaxDataSizeMB,
		SummariesVolumeMB: 0,
	}
	return RenderPlan(plan, pr)
}

// RenderPlan builds volumes + all index / summary stanzas.
func RenderPlan(p model.PlanInput, res model.PlanResult) string {
	var b strings.Builder
	b.WriteString("# Generated by SCPcalc — review before production use\n")
	b.WriteString("# Formulas: knowledge pack docs/en/02 + docs/en/05\n")
	b.WriteString("# Event-size defaults are editable planning estimates.\n")
	if res.IndexerPeers > 1 {
		fmt.Fprintf(&b, "# Size fields below are PER PEER (cluster total ÷ N_IDX=%d).\n", res.IndexerPeers)
	}
	b.WriteString("\n")

	fmt.Fprintf(&b, "[volume:hotwarm]\npath = %s\nmaxVolumeDataSizeMB = %d\n# Hot/warm (+ DMA colocated by default on reference hardware)\n\n", p.HotPath, max64(res.HotVolumeMB, 1))
	fmt.Fprintf(&b, "[volume:cold]\npath = %s\nmaxVolumeDataSizeMB = %d\n# Cold searchable retention\n\n", p.ColdPath, max64(res.ColdVolumeMB, 1))

	sumMB := res.SummariesVolumeMB
	if sumMB <= 0 && (p.WantDMA() || hasSummary(res)) {
		sumMB = 1
	}
	if sumMB > 0 {
		fmt.Fprintf(&b, "[volume:summaries]\npath = %s\nmaxVolumeDataSizeMB = %d\n# Prefer SSD/NVMe; keep separate from cold (DMA/tstats + summary indexes)\n\n", p.SummariesPath, max64(sumMB, 1))
	}

	if p.SmartStore {
		remote := strings.TrimSpace(p.RemotePath)
		if remote == "" {
			remote = "s3://YOUR_BUCKET/splunk"
		}
		fmt.Fprintf(&b, "# --- SmartStore (docs/en/02 §5) ---\n")
		fmt.Fprintf(&b, "# Remote_Store_GB ≈ D × R × Comp (see design.remote_store_gb).\n")
		fmt.Fprintf(&b, "# Each cluster needs a unique remote path. Network target: 10 Gbps/indexer.\n")
		fmt.Fprintf(&b, "[volume:remote]\nstorageType = remote\npath = %s\n# Configure remote.s3.* (or provider) credentials in indexes.conf / server.conf as required\n\n", remote)
	}

	emitTstats := p.WantDMA()
	for _, ix := range res.Indexes {
		writeIndex(&b, p, ix.IndexName, ix.HomePathMaxDataSizeMB, ix.MaxTotalDataSizeMB, ix.FrozenTimePeriodInSecs, ix.MaxDataSize, "primary", emitTstats)
		if ix.SummaryIndexName != "" && ix.SummaryMaxTotalMB > 0 {
			writeIndex(&b, p, ix.SummaryIndexName, ix.SummaryHomeMaxMB, ix.SummaryMaxTotalMB, ix.SummaryFrozenSecs, "auto", "summary", false)
		}
	}
	return b.String()
}

func hasSummary(res model.PlanResult) bool {
	for _, ix := range res.Indexes {
		if ix.SummaryIndexName != "" {
			return true
		}
	}
	return false
}

func writeIndex(b *strings.Builder, p model.PlanInput, name string, homeMB, totalMB, frozenSecs int64, maxData, kind string, emitTstats bool) {
	idx := SanitizeIndex(name)
	fmt.Fprintf(b, "[%s]\n", idx)
	if kind == "summary" {
		fmt.Fprintf(b, "homePath = volume:summaries/%s/db\n", idx)
		fmt.Fprintf(b, "coldPath = volume:summaries/%s/colddb\n", idx)
		fmt.Fprintf(b, "thawedPath = %s/%s/thaweddb\n", strings.TrimRight(p.SummariesPath, "/"), idx)
	} else if p.SmartStore {
		fmt.Fprintf(b, "homePath = volume:hotwarm/%s/db\n", idx)
		fmt.Fprintf(b, "coldPath = volume:hotwarm/%s/colddb\n", idx) // SmartStore: warm typically local cache path family
		fmt.Fprintf(b, "thawedPath = %s/%s/thaweddb\n", strings.TrimRight(p.ColdPath, "/"), idx)
		fmt.Fprintf(b, "remotePath = volume:remote/%s\n", idx)
	} else {
		fmt.Fprintf(b, "homePath = volume:hotwarm/%s/db\n", idx)
		fmt.Fprintf(b, "coldPath = volume:cold/%s/colddb\n", idx)
		fmt.Fprintf(b, "thawedPath = %s/%s/thaweddb\n", strings.TrimRight(p.ColdPath, "/"), idx)
	}
	fmt.Fprintf(b, "homePath.maxDataSizeMB = %d\n", homeMB)
	fmt.Fprintf(b, "maxTotalDataSizeMB = %d\n", totalMB)
	fmt.Fprintf(b, "frozenTimePeriodInSecs = %d\n", frozenSecs)
	fmt.Fprintf(b, "maxDataSize = %s\n", maxData)
	if p.ArchiveFrozen {
		fmt.Fprintf(b, "coldToFrozenDir = %s/%s/frozendb\n", strings.TrimRight(p.FrozenPath, "/"), idx)
	} else {
		b.WriteString("# coldToFrozenDir omitted — default freeze deletes (set archive_frozen=true to archive)\n")
	}
	if kind == "primary" && emitTstats {
		fmt.Fprintf(b, "tstatsHomePath = volume:summaries/%s/datamodel_summary\n", idx)
	}
	b.WriteString("\n")
}

// SanitizeIndex maps a label to a safe indexes.conf stanza name.
func SanitizeIndex(name string) string {
	name = strings.TrimSpace(name)
	if name == "" {
		return "windows"
	}
	var out strings.Builder
	for _, r := range name {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' || r == '-' {
			out.WriteRune(r)
		} else {
			out.WriteByte('_')
		}
	}
	s := out.String()
	if s == "" {
		return "windows"
	}
	return s
}

func max64(a, b int64) int64 {
	if a > b {
		return a
	}
	return b
}
