#!/usr/bin/env bash
# Sync browser UI (+ WASM) to repo-root calc/ for GitHub Pages (static, no server).
# Keeps the tracked calc/README.md (does not overwrite it).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO="$(cd "$ROOT/.." && pwd)"
DEST="$REPO/calc"
README_SAVE=""

python3 "$ROOT/scripts/assemble_html.py"
"$ROOT/scripts/build_wasm.sh"

if [[ -f "$DEST/README.md" ]]; then
  README_SAVE="$(mktemp)"
  cp "$DEST/README.md" "$README_SAVE"
fi

rm -rf "$DEST"
mkdir -p "$DEST"
cp -a "$ROOT/web/." "$DEST/"
rm -f "$DEST/embed.go"
# Source-only modular HTML (assembled into index.html for runtime).
rm -rf "$DEST/html"

if [[ -n "$README_SAVE" ]]; then
  mv "$README_SAVE" "$DEST/README.md"
else
  cat > "$DEST/README.md" <<'EOF'
# scpcalc Web UI (static / WASM)

Generated by `make pages-calc` (gitignored except this README).

- Engine runs in the browser (Go → WebAssembly).
- CI deploys on push to main/master — see `.github/workflows/scpcalc-pages.yml`.
- Pages URL: `/calc/`
EOF
fi

echo "Pages calc synced → $DEST"
